config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  root 'sessions#new'
  #get '/tops', to: 'tops#index'
  resources :customers
  resources :tops
  resources :kartes
  resources :diseases do
    collection do
      get 'search'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/desease.rb
class Desease < ApplicationRecord
end

app/models/karte.rb
class Karte < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  def self.search(search)
      if search
        Post.where(['content LIKE ?', "%#{search}%"])
      else
        Post.all
      end
    end
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def new
    @customer = Customer.new
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def create
    Customer.create(customer_params)
    redirect_to new_customer_path
  end

  private
  def customer_params
    params.require(:customer).permit(:medical_record_number, :animal_major_classification, :animal_subcategory, :name, :last_visit_date)
  end
end

app/controllers/diseases_controller.rb
class DiseasesController < ApplicationController
  before_action :set_q, only: [:index, :search]

  def index
    @deseases = Desease.all
  end

  def search
    @results = @q.result
  end

  def show
  end

  private

  def set_q
    @q = Desease.ransack(params[:q])
  end

end

app/controllers/kartes_controller.rb
class KartesController < ApplicationController
  def index
    @kartes = Karte.all
  end

  def new
    @karte = Karte.new
  end

  def show
    @karte = Karte.find(params[:id])
  end

  def create
    Karte.create(karte_params)
    redirect_to new_karte_path
  end

  private
  def karte_params
    params.require(:karte).permit(:karte_number, :patient_number, :s, :o, :a, :p)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def search
    #Viewのformで取得したパラメータをモデルに渡す
    @posts = Post.search(params[:search])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # ログイン成功した場合
      session[:user_id] = user.id
      redirect_to tops_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/diseases_helper.rb
module DiseasesHelper
end

app/helpers/kartes_helper.rb
module KartesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def logged_in?
    current_user.present?
  end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/customers/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PETTRA</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
		<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<%= image_tag 'image.png', class: "tops_field" %>
			<a class="navbar-brand" href="tops">Home</a>
			<a class="navbar-brand" href="#">About</a>
			<a class="navbar-brand" href="#">Features</a>
			<a class="navbar-brand" href="#">Princing</a>
			<a class="navbar-brand" href="#">Contact us</a>
		</div>
</nav>

  </header>
<h1>顧客情報</h1>
<table class="table table-hover">
  <tr>
    <th>カルテ番号</th>
    <th>動物大分類</th>
    <th>動物小分類</th>
    <th>名前</th>
    <th>最終来院日</th>
  </tr>
<% @customers.each do |customer| %>
  <tr>
    <td><%= customer.medical_record_number %></td>
    <td><%= customer.animal_major_classification %></td>
    <td><%= customer.animal_subcategory %></td>
    <td><%= customer.name %></td>
    <td><%= customer.last_visit_date %></td>

  </tr>
<% end %>
</table>

app/views/customers/new.html.erb
<%= form_with(model: @customer, local: true) do |form| %>
  <div class="medical_record_number">
    <%= form.label :カルテ番号 %>
    <%= form.text_field :medical_record_number %>
  </div>
  <div class="animal_major_classification">
    <%= form.label :動物大分類 %>
    <%= form.text_field :animal_major_classification %>
  </div>
  <div class="animal_subcategory">
    <%= form.label :動物小分類 %>
    <%= form.text_field :animal_subcategory %>
  </div>
  <div class="name">
    <%= form.label :名前 %>
    <%= form.text_field :name %>
  </div>
  <div class="last_visit_date">
    <%= form.label :最終来院日 %>
    <%= form.date_field :last_visit_date %>
  </div>
  <%= form.submit %>
<% end %>
<%= link_to '戻る', customers_path %>

<footer>
  <p>© 2021 PETTRA Corp.</p>
</footer>

app/views/customers/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PETTRA</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
		<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<%= image_tag 'image.png', class: "tops_field" %>
			<a class="navbar-brand" href="tops">Home</a>
			<a class="navbar-brand" href="#">About</a>
			<a class="navbar-brand" href="#">Features</a>
			<a class="navbar-brand" href="#">Princing</a>
			<a class="navbar-brand" href="#">Contact us</a>
		</div>
</nav>

  </header>
<h1>患者詳細画面</h1>
<p>患者番号: <%= @customer.medical_record_number %></p>
<p>動物大分類: <%= @customer.animal_major_classification %></p>
<p>動物小分類: <%= @customer.animal_subcategory %></p>
<p>名前: <%= @customer.name %></p>
<p>最終来院日: <%= @customer.last_visit_date %></p>

<td><%= link_to "新規カルテ", new_karte_path  %></td>

app/views/diseases/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PETTRA</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
		<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
		<%= image_tag 'image.png', class: "tops_field" %>
			<a class="navbar-brand" href="tops">Home</a>
			<a class="navbar-brand" href="#">About</a>
			<a class="navbar-brand" href="#">Features</a>
			<a class="navbar-brand" href="#">Princing</a>
			<a class="navbar-brand" href="#">Contact us</a>
		</div>

</nav>

  </header>

<h1>傷病検索</h1>
<%= search_form_for @q, url: search_diseases_path do |f| %>
  <%= f.label :disease_cont, '傷病名' %>
  <%= f.search_field :disease_cont %>
  <br>
  <%= f.submit '検索' %>
<% end %>


<footer>
  <p>© 2021 PETTRA Corp.</p>
</footer>

app/views/diseases/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PETTRA</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
		<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
		<%= image_tag 'image.png', class: "tops_field" %>
			<a class="navbar-brand" href="tops">Home</a>
			<a class="navbar-brand" href="#">About</a>
			<a class="navbar-brand" href="#">Features</a>
			<a class="navbar-brand" href="#">Princing</a>
			<a class="navbar-brand" href="#">Contact us</a>
		</div>

</nav>

  </header>
<br>
<h1>電子カルテ</h1>
<button id="start-btn">start</button>
<button id="stop-btn">stop</button>
<div id="result-div"></div>

<script>
  
  const startBtn = document.querySelector('#start-btn');
  const stopBtn = document.querySelector('#stop-btn');
  const resultDiv = document.querySelector('#result-div');

  SpeechRecognition = webkitSpeechRecognition || SpeechRecognition;
  let recognition = new SpeechRecognition();

  recognition.lang = 'ja-JP';
  recognition.interimResults = true;
  recognition.continuous = true;

  let finalTranscript = ''; // 確定した(黒の)認識結果

  recognition.onresult = (event) => {
    let interimTranscript = ''; // 暫定(灰色)の認識結果
    for (let i = event.resultIndex; i < event.results.length; i++) {
      let transcript = event.results[i][0].transcript;
      if (event.results[i].isFinal) {
        finalTranscript += transcript;
      } else {
        interimTranscript = transcript;
      }
    }
    resultDiv.innerHTML = finalTranscript + '<i style="color:#ddd;">' + interimTranscript + '</i>';
  }

  startBtn.onclick = () => {
    recognition.start();
  }
  stopBtn.onclick = () => {
    recognition.stop();
  }
</script>

app/views/diseases/search.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PETTRA</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
		<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
		<%= image_tag 'image.png', class: "tops_field" %>
			<a class="navbar-brand" href="tops">Home</a>
			<a class="navbar-brand" href="#">About</a>
			<a class="navbar-brand" href="#">Features</a>
			<a class="navbar-brand" href="#">Princing</a>
			<a class="navbar-brand" href="#">Contact us</a>
		</div>

</nav>

  </header>

<h1>検索結果</h1>
<table>
  <thead>
    <tr>
      <th nowrap>動物分類</th>
      <th>病名</th>
      <th>症状</th>
      <th>症例</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |desease| %>
      <tr>
        <td><%= desease.animal_category %></td>
        <td><%= desease.disease %></td>
        <td nowrap><%= desease.sym_part %></td>
        <td><%= desease.symptom %></td>


      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Top', diseases_path %>

app/views/kartes/new.html.erb
<%= form_with(model: @karte, local: true) do |form| %>
  <div class="karte_number">
    <%= form.label :カルテ番号 %>
    <%= form.text_field :karte_number %>
  </div>
  <div class="patient_number">
    <%= form.label :患者番号 %>
    <%= form.text_field :patient_number %>
  </div>
  <div id="result-div" class="s">
    <%= form.label :test %>
    <%= form.text_field :s %>
  </div>

  <div class="o">
    <%= form.label :o %>
    <%= form.text_field :o %>
  </div>
  <div class="a">
    <%= form.label :a %>
    <%= form.text_field :a %>
  </div>
  <div class="p">
    <%= form.label :p %>
    <%= form.text_field :p %>
  </div>
  <%= form.submit %>
<% end %>
<%= link_to '戻る', customers_path %>
<button id="start-btn">start</button>
<button id="stop-btn">stop</button>

<script>

  const startBtn = document.querySelector('#start-btn');
  const stopBtn = document.querySelector('#stop-btn');
  const resultDiv = document.querySelector('#result-div');

  SpeechRecognition = webkitSpeechRecognition || SpeechRecognition;
  let recognition = new SpeechRecognition();

  recognition.lang = 'ja-JP';
  recognition.interimResults = true;
  recognition.continuous = true;

  let finalTranscript = ''; // 確定した(黒の)認識結果

  recognition.onresult = (event) => {
    let interimTranscript = ''; // 暫定(灰色)の認識結果
    for (let i = event.resultIndex; i < event.results.length; i++) {
      let transcript = event.results[i][0].transcript;
      if (event.results[i].isFinal) {
        finalTranscript += transcript;
      } else {
        interimTranscript = transcript;
      }
    }
    resultDiv.innerHTML = '<label for="karte_s">S</label><input type="text" name="karte[s]" id="karte_s" value = "' + finalTranscript + interimTranscript + '">';
  }

  startBtn.onclick = () => {
    recognition.start();
  }
  stopBtn.onclick = () => {
    recognition.stop();
  }
</script>

<footer>
  <p>© 2021 PETTRA Corp.</p>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PETTRA</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>
      <% if logged_in? %>
        <%= link_to "ログアウト", session_path(current_user.id), method: :delete %>
      <% else %>
        <%= link_to "ログイン", new_session_path %>
      <% end %>
      <%= yield %>
    </body>


</html>

app/views/tops/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PETTRA</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
		<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
		<%= image_tag 'image.png', class: "tops_field" %>
			<a class="navbar-brand" href="tops">Home</a>
			<a class="navbar-brand" href="#">About</a>
			<a class="navbar-brand" href="#">Features</a>
			<a class="navbar-brand" href="#">Princing</a>
			<a class="navbar-brand" href="#">Contact us</a>
		</div>

</nav>

  </header>

    <br>
    <br>
    <div class="dropdown">
  <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
    顧客情報
  </a>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
    <li><a class="dropdown-item" href="#">Action</a></li>
    <li><a class="dropdown-item" href="#">Another action</a></li>
    <li><a class="dropdown-item" href="#">Something else here</a></li>
  </ul>
    <a href="customers" class="btn btn--orange">顧客情報</a>
    <a href="" class="btn btn--white">予約情報</a>
    <a href="" class="btn btn--orange">薬剤管理</a>
    <br>
    <br>
    <br>
  </div>
  <div class="dropdown">
  <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
  予約情報
  </a>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
  <li><a class="dropdown-item" href="#">Action</a></li>
  <li><a class="dropdown-item" href="#">Another action</a></li>
  <li><a class="dropdown-item" href="#">Something else here</a></li>
  </ul>
    <a href="diseases" class="btn btn--white">診察カルテ</a>
    <a href="" class="btn btn--orange">入院管理</a>
    <a href="" class="btn btn--white">会計情報</a>
    <br>
    <br>
    <br>
  </div>
  <div class="dropdown">
<a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
  薬剤管理
</a>
<ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
  <li><a class="dropdown-item" href="#">Action</a></li>
  <li><a class="dropdown-item" href="#">Another action</a></li>
  <li><a class="dropdown-item" href="#">Something else here</a></li>
</ul>
    <a href="" class="btn btn--orange">DM管理</a>
    <a href="" class="btn btn--white">オリジナル辞書登録</a>
    <a href="" class="btn btn--orange">メニュー追加</a>
</div>
<br>
<br>
<div class="dropdown">
<a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
診察カルテ
</a>
<ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
  <li><a class="dropdown-item" href="#">Action</a></li>
  <li><a class="dropdown-item" href="#">Another action</a></li>
  <li><a class="dropdown-item" href="#">Something else here</a></li>
</ul>
</div>


  </body>
  <%= yield %>

    <footer>
      <p>© 2021 PETTRA Corp.</p>
    </footer>

</html>

app/views/tops/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PETTRA</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
		<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
		<%= image_tag 'image.png', class: "tops_field" %>
			<a class="navbar-brand" href="tops">Home</a>
			<a class="navbar-brand" href="#">About</a>
			<a class="navbar-brand" href="#">Features</a>
			<a class="navbar-brand" href="#">Princing</a>
			<a class="navbar-brand" href="#">Contact us</a>
		</div>

</nav>

  </header>
<br>
<h1>電子カルテ</h1>
<button id="start-btn">start</button>
<button id="stop-btn">stop</button>
<div id="result-div"></div>

<script>
  const startBtn = document.querySelector('#start-btn');
  const stopBtn = document.querySelector('#stop-btn');
  const resultDiv = document.querySelector('#result-div');

  SpeechRecognition = webkitSpeechRecognition || SpeechRecognition;
  let recognition = new SpeechRecognition();

  recognition.lang = 'ja-JP';
  recognition.interimResults = true;
  recognition.continuous = true;

  let finalTranscript = ''; // 確定した(黒の)認識結果

  recognition.onresult = (event) => {
    let interimTranscript = ''; // 暫定(灰色)の認識結果
    for (let i = event.resultIndex; i < event.results.length; i++) {
      let transcript = event.results[i][0].transcript;
      if (event.results[i].isFinal) {
        finalTranscript += transcript;
      } else {
        interimTranscript = transcript;
      }
    }
    resultDiv.innerHTML = finalTranscript + '<i style="color:#ddd;">' + interimTranscript + '</i>';
  }

  startBtn.onclick = () => {
    recognition.start();
  }
  stopBtn.onclick = () => {
    recognition.stop();
  }
</script>